# Generated by Django 6.0.1 on 2026-02-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='vehicle_number',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='next_service_km',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='odometer_reading',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle_brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle_model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
    ]
