# Generated by Django 6.0.1 on 2026-02-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecareapp', '0002_maintenancerecord_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
